version: '3.9'

services:
  psql:
    image: postgres
    container_name: psql
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    stdin_open: true
    tty: true
    entrypoint: ["echo", "psql service is ready to use..."]
