name: docker-compose run

on:
  pull_request:
    branches: ["main"]

env:
  POSTGRES_USER: guest
  POSTGRES_PASSWORD: guest
  PGPASSWORD: guest
  POSTGRES_DB: example

jobs:
  compose-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Up docker-compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for PostgreSQL to become available
        run: |
          until docker-compose -f docker-compose.yml exec db pg_isready -U "$POSTGRES_USER"; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Run psql
        run: docker-compose -f docker-compose.yml run --rm --entrypoint psql psql -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT NOW();"
